//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoSpeedUI.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MoSpeedUI.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string IntroText {
            get {
                return ResourceManager.GetString("IntroText", resourceCulture);
            }
        }
        
        public static string DragBox {
            get {
                return ResourceManager.GetString("DragBox", resourceCulture);
            }
        }
        
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        public static string DragEnter {
            get {
                return ResourceManager.GetString("DragEnter", resourceCulture);
            }
        }
        
        public static string DragInvalid {
            get {
                return ResourceManager.GetString("DragInvalid", resourceCulture);
            }
        }
        
        public static string FilePickerTitle {
            get {
                return ResourceManager.GetString("FilePickerTitle", resourceCulture);
            }
        }
        
        public static string FilePickerDef {
            get {
                return ResourceManager.GetString("FilePickerDef", resourceCulture);
            }
        }
        
        public static string FileListDesc {
            get {
                return ResourceManager.GetString("FileListDesc", resourceCulture);
            }
        }
        
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        public static string TargetPlatform {
            get {
                return ResourceManager.GetString("TargetPlatform", resourceCulture);
            }
        }
        
        public static string PlatformSpecific {
            get {
                return ResourceManager.GetString("PlatformSpecific", resourceCulture);
            }
        }
        
        public static string C64Specific {
            get {
                return ResourceManager.GetString("C64Specific", resourceCulture);
            }
        }
        
        public static string NoExpansion {
            get {
                return ResourceManager.GetString("NoExpansion", resourceCulture);
            }
        }
        
        public static string ThreeKExpansion {
            get {
                return ResourceManager.GetString("ThreeKExpansion", resourceCulture);
            }
        }
        
        public static string EightKExpansion {
            get {
                return ResourceManager.GetString("EightKExpansion", resourceCulture);
            }
        }
        
        public static string MemoryConfig {
            get {
                return ResourceManager.GetString("MemoryConfig", resourceCulture);
            }
        }
        
        public static string JSPlatformConfig {
            get {
                return ResourceManager.GetString("JSPlatformConfig", resourceCulture);
            }
        }
        
        public static string ProgramStart {
            get {
                return ResourceManager.GetString("ProgramStart", resourceCulture);
            }
        }
        
        public static string VarsStart {
            get {
                return ResourceManager.GetString("VarsStart", resourceCulture);
            }
        }
        
        public static string StringMemEnd {
            get {
                return ResourceManager.GetString("StringMemEnd", resourceCulture);
            }
        }
        
        public static string RuntimeStart {
            get {
                return ResourceManager.GetString("RuntimeStart", resourceCulture);
            }
        }
        
        public static string DecimalOrHexWDefault {
            get {
                return ResourceManager.GetString("DecimalOrHexWDefault", resourceCulture);
            }
        }
        
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        public static string MemHoles {
            get {
                return ResourceManager.GetString("MemHoles", resourceCulture);
            }
        }
        
        public static string CompressLvl {
            get {
                return ResourceManager.GetString("CompressLvl", resourceCulture);
            }
        }
        
        public static string SrcCdePrsc {
            get {
                return ResourceManager.GetString("SrcCdePrsc", resourceCulture);
            }
        }
        
        public static string LoopHandling {
            get {
                return ResourceManager.GetString("LoopHandling", resourceCulture);
            }
        }
        
        public static string LinkerOptBox {
            get {
                return ResourceManager.GetString("LinkerOptBox", resourceCulture);
            }
        }
        
        public static string CompressLvl0 {
            get {
                return ResourceManager.GetString("CompressLvl0", resourceCulture);
            }
        }
        
        public static string CompressLvl1 {
            get {
                return ResourceManager.GetString("CompressLvl1", resourceCulture);
            }
        }
        
        public static string CompressLvl2 {
            get {
                return ResourceManager.GetString("CompressLvl2", resourceCulture);
            }
        }
        
        public static string CompressLvl3 {
            get {
                return ResourceManager.GetString("CompressLvl3", resourceCulture);
            }
        }
        
        public static string EndAdd {
            get {
                return ResourceManager.GetString("EndAdd", resourceCulture);
            }
        }
        
        public static string PSPlatformConfig {
            get {
                return ResourceManager.GetString("PSPlatformConfig", resourceCulture);
            }
        }
        
        public static string PyPlatformConfig {
            get {
                return ResourceManager.GetString("PyPlatformConfig", resourceCulture);
            }
        }
        
        public static string DecimalOrHex {
            get {
                return ResourceManager.GetString("DecimalOrHex", resourceCulture);
            }
        }
        
        public static string SrcCdeNone {
            get {
                return ResourceManager.GetString("SrcCdeNone", resourceCulture);
            }
        }
        
        public static string SrcCdeLower {
            get {
                return ResourceManager.GetString("SrcCdeLower", resourceCulture);
            }
        }
        
        public static string SrcCdeFlip {
            get {
                return ResourceManager.GetString("SrcCdeFlip", resourceCulture);
            }
        }
        
        public static string LoopHandlingRemove {
            get {
                return ResourceManager.GetString("LoopHandlingRemove", resourceCulture);
            }
        }
        
        public static string LoopHandlingRetain {
            get {
                return ResourceManager.GetString("LoopHandlingRetain", resourceCulture);
            }
        }
        
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        public static string AddMemHole {
            get {
                return ResourceManager.GetString("AddMemHole", resourceCulture);
            }
        }
        
        public static string Compile {
            get {
                return ResourceManager.GetString("Compile", resourceCulture);
            }
        }
        
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        public static string SetupText {
            get {
                return ResourceManager.GetString("SetupText", resourceCulture);
            }
        }
        
        public static string SetupStep1 {
            get {
                return ResourceManager.GetString("SetupStep1", resourceCulture);
            }
        }
        
        public static string DwnldMS {
            get {
                return ResourceManager.GetString("DwnldMS", resourceCulture);
            }
        }
        
        public static string FndMS {
            get {
                return ResourceManager.GetString("FndMS", resourceCulture);
            }
        }
        
        public static string SetupStep2a {
            get {
                return ResourceManager.GetString("SetupStep2a", resourceCulture);
            }
        }
        
        public static string SetupStep2b {
            get {
                return ResourceManager.GetString("SetupStep2b", resourceCulture);
            }
        }
        
        public static string DwnldMSBtn {
            get {
                return ResourceManager.GetString("DwnldMSBtn", resourceCulture);
            }
        }
        
        public static string FndMSBtn {
            get {
                return ResourceManager.GetString("FndMSBtn", resourceCulture);
            }
        }
        
        public static string FndMSWm {
            get {
                return ResourceManager.GetString("FndMSWm", resourceCulture);
            }
        }
        
        public static string FinishSetup {
            get {
                return ResourceManager.GetString("FinishSetup", resourceCulture);
            }
        }
        
        public static string MSPickerTitle {
            get {
                return ResourceManager.GetString("MSPickerTitle", resourceCulture);
            }
        }
        
        public static string MSPickerInvalidPath {
            get {
                return ResourceManager.GetString("MSPickerInvalidPath", resourceCulture);
            }
        }
        
        public static string MSPickerNoMS {
            get {
                return ResourceManager.GetString("MSPickerNoMS", resourceCulture);
            }
        }
        
        public static string MSPickerSuccess {
            get {
                return ResourceManager.GetString("MSPickerSuccess", resourceCulture);
            }
        }
        
        public static string MSDownloadSuccess {
            get {
                return ResourceManager.GetString("MSDownloadSuccess", resourceCulture);
            }
        }
        
        public static string Unzip {
            get {
                return ResourceManager.GetString("Unzip", resourceCulture);
            }
        }
        
        public static string MSDownloadError {
            get {
                return ResourceManager.GetString("MSDownloadError", resourceCulture);
            }
        }
        
        public static string CollectingInfo {
            get {
                return ResourceManager.GetString("CollectingInfo", resourceCulture);
            }
        }
        
        public static string JavaNotFoundError {
            get {
                return ResourceManager.GetString("JavaNotFoundError", resourceCulture);
            }
        }
        
        public static string WrongJavaVersionException {
            get {
                return ResourceManager.GetString("WrongJavaVersionException", resourceCulture);
            }
        }
        
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        public static string JavaGenericError {
            get {
                return ResourceManager.GetString("JavaGenericError", resourceCulture);
            }
        }
        
        public static string JavaWrongVersion {
            get {
                return ResourceManager.GetString("JavaWrongVersion", resourceCulture);
            }
        }
        
        public static string Compiling {
            get {
                return ResourceManager.GetString("Compiling", resourceCulture);
            }
        }
        
        public static string UsingArguments {
            get {
                return ResourceManager.GetString("UsingArguments", resourceCulture);
            }
        }
        
        public static string SaveFilePickerTitle {
            get {
                return ResourceManager.GetString("SaveFilePickerTitle", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string AdvWelcome {
            get {
                return ResourceManager.GetString("AdvWelcome", resourceCulture);
            }
        }
        
        public static string AdvWatermark {
            get {
                return ResourceManager.GetString("AdvWatermark", resourceCulture);
            }
        }
        
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        public static string OpenParameterWiki {
            get {
                return ResourceManager.GetString("OpenParameterWiki", resourceCulture);
            }
        }
        
        public static string WikiUrl {
            get {
                return ResourceManager.GetString("WikiUrl", resourceCulture);
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string LicenseNote {
            get {
                return ResourceManager.GetString("LicenseNote", resourceCulture);
            }
        }
        
        public static string OpenGit {
            get {
                return ResourceManager.GetString("OpenGit", resourceCulture);
            }
        }
        
        public static string ReportBug {
            get {
                return ResourceManager.GetString("ReportBug", resourceCulture);
            }
        }
        
        public static string CompileCancel {
            get {
                return ResourceManager.GetString("CompileCancel", resourceCulture);
            }
        }
    }
}
