//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoSpeedUI.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MoSpeedUI.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string IntroText {
            get {
                return ResourceManager.GetString("IntroText", resourceCulture);
            }
        }
        
        public static string DragBox {
            get {
                return ResourceManager.GetString("DragBox", resourceCulture);
            }
        }
        
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        public static string DragEnter {
            get {
                return ResourceManager.GetString("DragEnter", resourceCulture);
            }
        }
        
        public static string DragInvalid {
            get {
                return ResourceManager.GetString("DragInvalid", resourceCulture);
            }
        }
        
        public static string FilePickerTitle {
            get {
                return ResourceManager.GetString("FilePickerTitle", resourceCulture);
            }
        }
        
        public static string FilePickerDef {
            get {
                return ResourceManager.GetString("FilePickerDef", resourceCulture);
            }
        }
        
        public static string FileListDesc {
            get {
                return ResourceManager.GetString("FileListDesc", resourceCulture);
            }
        }
        
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        public static string TargetPlatform {
            get {
                return ResourceManager.GetString("TargetPlatform", resourceCulture);
            }
        }
        
        public static string PlatformSpecific {
            get {
                return ResourceManager.GetString("PlatformSpecific", resourceCulture);
            }
        }
        
        public static string C64Specific {
            get {
                return ResourceManager.GetString("C64Specific", resourceCulture);
            }
        }
    }
}
